In [6]:
import pandas as pd
data = pd.read_csv('data_merged.csv', sep=';')
data

,Unnamed: 0.1,Unnamed: 0,question,selections,options,source,value_us,value_uk,index_us,index_uk,answer_us,answer_uk,category,# of options,question type,category_group
0,0,0.0,Which statement comes closer to your own views...,"'United States': [0.0, 0.0, 0.54, 0.0, 0.0, 0....",['Using overwhelming military force is the bes...,GAS,0.540000,0.350254,2.0,7.0,Many of the problems facing our country can be...,"When dealing with major international issues, ...",D. Politics and policy,9.0,Likert Scale,Politics and Governance
1,1,1.0,"In your opinion, how strong a sense of Islamic...","'United States': [0.24705882352941178, 0.44705...","['Very strong', 'Fairly strong', 'Not too stro...",GAS,0.447059,0.539326,1.0,1.0,Fairly strong,Fairly strong,B. Religion and spirituality,4.0,Likert Scale,"Economy, Health, and Environment"
2,2,2.0,Do you think this change in the working condit...,"'United States': [0.23157894736842105, 0.76842...","['Largely more connected', 'Other reasons']",GAS,0.768421,0.645161,1.0,1.0,Other reasons,Other reasons,N. Economy and work,2.0,Likert Scale,"Economy, Health, and Environment"
3,3,3.0,Do you think that using military force against...,"'United States': [0.22916666666666666, 0.45833...","['Often be justified', 'Sometimes be justified...",GAS,0.458333,0.510204,1.0,1.0,Sometimes be justified,Sometimes be justified,D. Politics and policy,4.0,Likert Scale,Politics and Governance
4,4,4.0,"On the subject of Iraq, did your country make ...","'United States': [0.5625, 0.4375], 'Britain': ...","['Right decision', 'Wrong decision']",GAS,0.562500,0.576087,0.0,1.0,Right decision,Wrong decision,D. Politics and policy,2.0,Binary Choice,Politics and Governance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,99,NaN,What was the first school founded in any country?,NaN,NaN,GPT / https://www.anadventurousworld.com/usa-t...,NaN,NaN,NaN,NaN,The first school in the United States was the ...,The first school in any country is believed to...,Education,NaN,Quiz question,"Media, Technology, and Education"
1646,100,NaN,When was the first public opening of a Disneyl...,NaN,NaN,GPT / https://www.anadventurousworld.com/usa-t...,NaN,NaN,NaN,NaN,The first public opening of a Disneyland theme...,The first Disneyland theme park was publicly o...,Entertainment,NaN,Quiz question,"Lifestyle, Entertainment, and Daily Living"
1647,101,NaN,Where was the first World Fair held in 1853?,NaN,NaN,GPT / https://www.anadventurousworld.com/usa-t...,NaN,NaN,NaN,NaN,The first World Fair in 1853 was held in New Y...,The first World Fair was not held in the UK in...,History,NaN,Quiz question,"Society, Culture, and Relationships"
1648,102,NaN,How many national championships has the most s...,NaN,NaN,GPT / https://www.anadventurousworld.com/usa-t...,NaN,NaN,NaN,NaN,The question is a bit ambiguous as it doesn't ...,The question is a bit vague as it doesn't spec...,Sports & Recreation,NaN,Quiz question,"Economy, Health, and Environment"
1649,103,NaN,What is the average annual pizza consumption p...,NaN,NaN,GPT / https://www.anadventurousworld.com/usa-t...,NaN,NaN,NaN,NaN,"In the United States, the average annual pizza...","In the United Kingdom, the average person cons...",Food & Drink,NaN,Quiz question,"Lifestyle, Entertainment, and Daily Living"

In [1]:
import pandas as pd
df_global_opinions = pd.read_csv('data_global_opinions_us_uk.csv', sep=';')
df_gpt = pd.read_csv('data_gpt.csv', sep=';')
df_quiz = pd.read_csv('data_quiz.csv', sep=';')

In [2]:
df_seedwords = pd.read_csv('../context generation/list_uk_us.csv', sep=';')

In [3]:
seedwords_lifestyle = df_seedwords[df_seedwords['category'] == 'Politics']
sample_df = seedwords_lifestyle[['uk_usage', 'us_usage']].sample(4)

uk = sample_df['uk_usage'].tolist()
us = sample_df['us_usage'].tolist()

print("UK_Words: ", uk)
print("US_Words: ", us)

UK_Words:  ['defence', 'fire brigade', 'bobby', 'labour']
US_Words:  ['defense', 'fire department', 'cop', 'labor']

In [4]:
df_seedwords['category'].value_counts().sort_index()

category
Economy & Well-being     32
Lifestyle               119
Politics                  4
Social Dynamics          17
Tech & Education         31
Name: count, dtype: int64

In [5]:
df_global_opinions['category'].value_counts().sort_index()

category
A. Social values and attitudes     72
B. Religion and spirituality       35
C. Science and technology          15
D. Politics and policy            371
E. Demographics                     7
F. Generations and age              1
G. International affairs           92
H. Internet and technology          8
I. Gender and LGBTQ                18
J. News habits and media           14
K. Immigration and migration        7
L. Family and relationships        23
M. Race and ethnicity              21
N. Economy and work               100
O. Regions and countries           15
P. Methodological research         12
Q. Security                        35
Name: count, dtype: int64

#### WVS Categories

In [6]:
## AVG words
#df_merged['word_count'] = df_merged['question'].apply(lambda x: len(str(x).split()))
#avg_words = df_merged['word_count'].mean()
#avg_words

In [7]:
filtered_df_wvs = df_global_opinions[df_global_opinions['source'] == 'WVS']
category_counts_wvs = filtered_df_wvs['category'].value_counts().sort_index() 
category_counts_wvs

category
A. Social values and attitudes    25
B. Religion and spirituality      13
C. Science and technology          7
D. Politics and policy            77
E. Demographics                    4
G. International affairs           1
H. Internet and technology         1
I. Gender and LGBTQ                8
J. News habits and media           3
K. Immigration and migration       2
L. Family and relationships       13
M. Race and ethnicity              2
N. Economy and work               24
O. Regions and countries           3
P. Methodological research         7
Q. Security                        9
Name: count, dtype: int64

#### Quiz categories

In [8]:
category_counts_quiz = df_quiz['category'].value_counts()
category_counts_quiz

category
Geography                   22
History                     22
Food & Drink                11
General Knowledge Trivia    10
Music & Arts                10
Literature                  10
Movies & TV Shows            9
Sports & Recreation          6
Animals                      1
Travel                       1
Education                    1
Entertainment                1
Name: count, dtype: int64

#### GAS Categories

In [9]:
filtered_df_gas = df_global_opinions[df_global_opinions['source'] == 'GAS']
category_counts_gas = filtered_df_gas['category'].value_counts().sort_index() 
category_counts_gas

category
A. Social values and attitudes     47
B. Religion and spirituality       22
C. Science and technology           8
D. Politics and policy            294
E. Demographics                     3
F. Generations and age              1
G. International affairs           91
H. Internet and technology          7
I. Gender and LGBTQ                10
J. News habits and media           11
K. Immigration and migration        5
L. Family and relationships        10
M. Race and ethnicity              19
N. Economy and work                76
O. Regions and countries           12
P. Methodological research          5
Q. Security                        26
Name: count, dtype: int64

#### GPT Categories

In [10]:
filtered_df_gpt = df_gpt[df_gpt['source'] == 'GPT-4 generated']
category_counts_gpt = filtered_df_gpt['category'].value_counts()
category_counts_gpt

category
Society & Relationships        108
Education & Knowledge          108
Entertainment & Arts            73
Food & Drink                    63
Fashion & Style                 35
Work & Career                   34
Travel & Commute                34
Family & Relationships          34
Holidays & Celebrations         33
Technology                      23
Environment & Nature            23
Health & Wellness               23
Spirituality & Religion         23
Housing & Lifestyle             23
Food,Family & Relationships     23
Cultural Preferences            20
Daily Activities                20
Name: count, dtype: int64

In [11]:
df_merged =  pd.concat([df_global_opinions, df_gpt, df_quiz])

In [12]:
### Category Grouping
def replace_category(val):
    if val in ['A. Social values and attitudes', 'L. Family and relationships', 'M. Race and ethnicity', 'I. Gender and LGBTQ',
                'Society & Relationships', 'Family & Relationships', 'Cultural Preferences', 'History', 'Literature']:
        return 'Society, Culture, and Relationships'
    elif val in ['D. Politics and policy', 'Q. Security', 'K. Immigration and migration']:
        return 'Politics and Governance'
    elif val in ['C. Science and technology','H. Internet and technology', 'J. News habits and media', 'P. Methodological research',
                'O. Regions and countries', 'E. Demographics', 'Education & Knowledge','Technology',
                'General Knowledge Trivia', 'Education']:
        return 'Media, Technology, and Education'
    elif val in ['Entertainment & Arts', 'Food & Drink', 'Holidays & Celebrations', 'Fashion & Style',
                'Work & Career', 'Travel & Commute', 'Housing & Lifestyle', 'Food,Family & Relationships', 
                'Daily Activities', 'Entertainment', 'Music & Arts', 'Movies & TV Shows', 'Animals', 'Travel']:
        return 'Lifestyle, Entertainment, and Daily Living'
    elif val in ['N. Economy and work', 'G. International affairs', 'B. Religion and spirituality', 
                'Spirituality & Religion', 'Environment & Nature', 'Health & Wellness', 'F. Generations and age',
                'Geography', 'Sports & Recreation']:
        return 'Economy, Health, and Environment'


# Apply the function to the column
df_merged['category_group'] = df_merged['category'].apply(replace_category)

df_global_opinions['category_group'] = df_global_opinions['category'].apply(replace_category)
df_gpt['category_group'] = df_gpt['category'].apply(replace_category)
df_quiz['category_group'] = df_quiz['category'].apply(replace_category)

In [13]:
print('All: ' + str(df_merged['category_group'].value_counts().sort_index()))
print('GPT: ' +str(df_gpt['category_group'].value_counts().sort_index()))
print('Quiz: ' + str(df_quiz['category_group'].value_counts().sort_index()))
print('GlobalQA: ' + str(df_global_opinions['category_group'].value_counts().sort_index()))

All: category_group
Economy, Health, and Environment              325
Lifestyle, Entertainment, and Daily Living    371
Media, Technology, and Education              213
Politics and Governance                       413
Society, Culture, and Relationships           328
Name: count, dtype: int64
GPT: category_group
Economy, Health, and Environment               69
Lifestyle, Entertainment, and Daily Living    338
Media, Technology, and Education              131
Society, Culture, and Relationships           162
Name: count, dtype: int64
Quiz: category_group
Economy, Health, and Environment              28
Lifestyle, Entertainment, and Daily Living    33
Media, Technology, and Education              11
Society, Culture, and Relationships           32
Name: count, dtype: int64
GlobalQA: category_group
Economy, Health, and Environment       228
Media, Technology, and Education        71
Politics and Governance                413
Society, Culture, and Relationships    134
Name: count, dtype: int64

In [14]:
print('All: ' + str(df_merged['question type'].value_counts().sort_index()))
print('GPT: ' +str(df_gpt['question type'].value_counts().sort_index()))
print('Quiz: ' + str(df_quiz['question type'].value_counts().sort_index()))
print('GlobalQA: ' + str(df_global_opinions['question type'].value_counts().sort_index()))

All: question type
Binary Choice      587
Likert Scale       708
Multiple Choice    163
Numerical Scale     30
Ordinal Scale       58
Quiz question      104
Name: count, dtype: int64
GPT: question type
Binary Choice      453
Likert Scale        89
Multiple Choice    108
Numerical Scale     11
Ordinal Scale       39
Name: count, dtype: int64
Quiz: question type
Quiz question    104
Name: count, dtype: int64
GlobalQA: question type
Binary Choice      134
Likert Scale       619
Multiple Choice     55
Numerical Scale     19
Ordinal Scale       19
Name: count, dtype: int64

In [15]:
### Count number of unique words in questions 
from collections import Counter
results = set()
df_global_opinions['question'].str.lower().str.split().apply(results.update)
print(len(results))

# 3644 for df_merged
# 2455 for df_globalQA

2455

In [16]:
questions = df_merged.question
questions.to_csv('questions.csv')

In [17]:
questions

0      Which statement comes closer to your own views...
1      In your opinion, how strong a sense of Islamic...
2      Do you think this change in the working condit...
3      Do you think that using military force against...
4      On the subject of Iraq, did your country make ...
                             ...
99     What was the first school founded in any country?
100    When was the first public opening of a Disneyl...
101         Where was the first World Fair held in 1853?
102    How many national championships has the most s...
103    What is the average annual pizza consumption p...
Name: question, Length: 1650, dtype: object

In [14]:
df_merged.to_csv('data_merged.csv', sep=";")

In [47]:
print("Global Opinions: " + str(df_global_opinions.shape[0]))
print("GPT generated: "+ str(df_gpt.shape[0]))
print("Quiz: "+ str(df_quiz.shape[0]))

Global Opinions: 846
GPT generated: 700
Quiz: 104

In [28]:
df_global_opinions['source'].value_counts()

source
GAS    647
WVS    199
Name: count, dtype: int64

In [7]:
df_global_opinions['question type'].value_counts()

question type
Likert Scale       619
Binary Choice      134
Multiple Choice     55
Numerical Scale     19
Ordinal Scale       19
Name: count, dtype: int64

In [8]:
df_gpt['question type'].value_counts()

question type
Binary Choice      453
Multiple Choice    108
Likert Scale        89
Ordinal Scale       39
Numerical Scale     11
Name: count, dtype: int64

In [9]:
df_global_opinions

,Unnamed: 0,question,selections,options,source,value_us,value_uk,index_us,index_uk,answer_us,answer_uk,category,# of options,question type
0,0,Which statement comes closer to your own views...,"'United States': [0.0, 0.0, 0.54, 0.0, 0.0, 0....",['Using overwhelming military force is the bes...,GAS,0.540000,0.350254,2,7,Many of the problems facing our country can be...,"When dealing with major international issues, ...",D. Politics and policy,9,Likert Scale
1,1,"In your opinion, how strong a sense of Islamic...","'United States': [0.24705882352941178, 0.44705...","['Very strong', 'Fairly strong', 'Not too stro...",GAS,0.447059,0.539326,1,1,Fairly strong,Fairly strong,B. Religion and spirituality,4,Likert Scale
2,2,Do you think this change in the working condit...,"'United States': [0.23157894736842105, 0.76842...","['Largely more connected', 'Other reasons']",GAS,0.768421,0.645161,1,1,Other reasons,Other reasons,N. Economy and work,2,Likert Scale
3,3,Do you think that using military force against...,"'United States': [0.22916666666666666, 0.45833...","['Often be justified', 'Sometimes be justified...",GAS,0.458333,0.510204,1,1,Sometimes be justified,Sometimes be justified,D. Politics and policy,4,Likert Scale
4,4,"On the subject of Iraq, did your country make ...","'United States': [0.5625, 0.4375], 'Britain': ...","['Right decision', 'Wrong decision']",GAS,0.562500,0.576087,0,1,Right decision,Wrong decision,D. Politics and policy,2,Binary Choice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,841,"For each of the following aspects, indicate ho...","'United States': [0.394, 0.40299999999999997, ...","['Very important', 'Rather important', 'Not ve...",WVS,0.403000,409.000000,1,0,Rather important,Very important,N. Economy and work,7,Likert Scale
842,842,"From your point of view, what have been the ef...","'United States': [0.201, 0.456, 0.329, 0.001, ...","['Disagree', 'Hard to say', 'Agree', ""Don't kn...",WVS,456.000000,0.410000,1,0,Hard to say,Disagree,N. Economy and work,6,Likert Scale
843,843,In which of the following things do you believ...,"'United States': [0.682, 0.284, 0.002, 0.032, ...","['Yes', 'No', ""Don't know"", 'No answer', 'Othe...",WVS,682.000000,525.000000,0,1,Yes,No,B. Religion and spirituality,5,Multiple Choice
844,844,"Do you agree, disagree or neither agree nor di...","'United States': [0.452, 0.306, 0.239, 0.0, 0....","['Agree', 'Disagree', 'Neither agree nor disag...",WVS,452.000000,0.453000,0,1,Agree,Disagree,D. Politics and policy,6,Likert Scale
845,845,Here are two statements people sometimes make ...,"'United States': [0.504, 0.386, 0.094, 0.0, 0....","['Protecting environment', 'Economy growth and...",WVS,504.000000,619.000000,0,0,Protecting environment,Protecting environment,D. Politics and policy,6,Multiple Choice

### Context generation

Prompt: Create a context for category x. Make it 0-100% British/American by implanting words out of df.